# Generated by Django 2.0.7 on 2018-08-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='s_address',
            field=models.CharField(default='', max_length=200, verbose_name='收货地址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='s_phone',
            field=models.CharField(default='', max_length=11, verbose_name='收货手机'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='地址'),
        ),
    ]
