# Generated by Django 2.0.7 on 2018-08-28 18:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180828_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': '书籍', 'verbose_name_plural': '书籍'},
        ),
        migrations.AlterField(
            model_name='books',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='详情'),
        ),
    ]
