# Generated by Django 2.0.7 on 2018-08-30 13:53

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180828_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='', max_length=20, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='books',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='详情'),
        ),
    ]
