# Generated by Django 2.0.7 on 2018-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180830_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='', max_length=20, verbose_name='标签'),
        ),
    ]
