# Generated by Django 2.0.7 on 2018-09-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
    ]
