# Generated by Django 2.0.7 on 2018-09-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_is_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='价格'),
        ),
    ]
