# Generated by Django 2.0.7 on 2018-09-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180907_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='', max_length=100, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='运费'),
        ),
    ]
